app:
  datasource:
    jdbc-url:  jdbc:mysql://localhost:3306/userdb
    username: root
    password: dick
spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: dickenstawanda@gmail.com
    password: 18765432
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false